# Generated by Django 5.1.1 on 2024-09-13 16:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=255, unique=True)),
                ('job_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('job_title', models.CharField(blank=True, max_length=500, null=True)),
                ('company_name', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('salary_raw', models.CharField(blank=True, max_length=500, null=True)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fixed_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(blank=True, max_length=500, null=True)),
                ('shift_and_schedule', models.CharField(blank=True, max_length=1000, null=True)),
                ('apply_link', models.URLField(blank=True, max_length=3000, null=True)),
                ('job_description_text', models.TextField(blank=True, null=True)),
                ('job_description_html', models.TextField(blank=True, null=True)),
                ('retrieved_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('scrape_session_id', models.CharField(max_length=500)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['job_id'], name='job_id_index'), models.Index(fields=['scrape_session_id'], name='scrape_session_index')],
            },
        ),
    ]
